imports:
    - { resource: tables.yml }

services:
    blog.core:
        class: phpbb_blog\blog\blog
        arguments:
            - @dbal.conn
            - @request
            - @blog.display
            - @blog.model.categories


    blog.display:
        class: phpbb_blog\blog\display
        arguments:
            - @controller.helper
            - @template
            - @user

    blog.model.categories:
        class: phpbb_blog\blog\model\bag\categories
        arguments:
            - %tables.blog.categories%
            - @dbal.conn

    blog.model.posts:
        class: phpbb_blog\blog\model\bag\posts
        arguments:
            - %tables.blog.posts%
            - @dbal.conn
