imports:
    - { resource: tables.yml }

services:
    phpbb_blog.blog.controller.core:
        class: phpbb_blog\blog\controller\core
        arguments:
            - @request
            - @blog.display

    phpbb_blog.blog.controller.update:
        class: phpbb_blog\blog\controller\update
        arguments:
            - @request
            - @blog.display

    phpbb_blog.blog.controller.moderate:
        class: phpbb_blog\blog\controller\moderate
        arguments:
            - @request
            - @blog.display

    phpbb_blog.blog.display:
        class: phpbb_blog\blog\display
        arguments:
            - @controller.helper
            - @template
            - @user
