imports:
    - { resource: tables.yml }

services:
    phpbb_blog.blog.controller.core:
        class: phpbb_blog\blog\controller\core
        arguments:
            - @request
            - @blog.display
            - @config
            - @phpbb_blog.blog.operator.posts
            - @phpbb_blog.blog.operator.tags
            - @phpbb_blog.blog.operator.categories
            - @phpbb_blog.blog.operator.comments
            - @template

    phpbb_blog.blog.display:
        class: phpbb_blog\blog\display
        arguments:
            - @controller.helper
            - @template
            - @user
